globalvar MYOKU;
nu chardata("vixen", "Myoku",,, 1,,,,, c_black);
MYOKU = global.textguy[$"vixen"];
MYOKU.addspr("NEUTRAL");
MYOKU.addspr("SMILING");
MYOKU.addspr("AMUSED");
MYOKU.addspr("EMBARRASSED");
MYOKU.addspr("THOUGHTFUL");
MYOKU.addspr("FROWNING");
MYOKU.addspr("ANNOYED");
MYOKU.addspr("SILLY");

globalvar AISAKO;
nu chardata("tanuki", "Aisako",,, 1,,,,, c_black);
AISAKO = global.textguy[$"tanuki"];
AISAKO.addspr("NEUTRAL");
AISAKO.addspr("SMILING");
AISAKO.addspr("AMUSED");
AISAKO.addspr("CONFUSED");
AISAKO.addspr("THOUGHTFUL");
AISAKO.addspr("FROWNING");
AISAKO.addspr("SMUG");

globalvar TAMAKO;
nu chardata("label", "Tamako",,, 1,,,,, c_black);
TAMAKO = global.textguy[$"label"];
TAMAKO.addspr("NEUTRAL");
TAMAKO.addspr("SMILING");
TAMAKO.addspr("AMUSED");
TAMAKO.addspr("CONFUSED");
TAMAKO.addspr("THOUGHTFUL");
TAMAKO.addspr("FROWNING");
TAMAKO.addspr("EMBARRASSED");