function txt_peace() { //silence.
	
	msg = [
	
	txt("It's a quiet, autumnal afternoon in the village as a kitsune is nestled in slumber."),
	txt("She dreams of what she considers to be better days, as her reverie wanders to faces that she hasn't been able to forget in her long life."),
	txt("Her dream fixates on one face in particular, one she thought to be lost in the far distance until recently."),
	txt("A face with a relationship she thought she had destroyed, or perhaps had never truly formed. She couldn't really figure out which."),
	txt("All that she knew is that sleep gave her nigh infinite second chances, that she'd drag until the waking world took her once more."),
	txt("Today gave her another one of those dreams, and another long sigh as she got out of bed, wondering where all the time had went."),
	txt("A sigh of disappointment, of satisfaction, or of relunctant acceptance, even she wasn't sure of."),
	txt("She wearily drags herself over to her small kitchen, preparing a basic meal for another basic day. As long as it gets her by, it was more than good enough in her eyes."),
	txt("She eats in prepared silence as she continues to spend another meal ruminating in her past, but as she finishes, a knock interrupts her train of thought."),
	txt("Six knocks, precisely. A specific pattern that would only come from a specific shrine maiden she knew very well."),
	txt("Come in.", MYOKU.NEUTRAL),
	txt("The door opens, revealing an indigo haired girl. Much, much younger than the kitsune, the Hakurei shrine maiden walks in with a smile."),
	txt("Good morning, Myoku!", TAMAKO.HAPPY),
	txt("Same to you, Tamako. Hope you've been doing well.", MYOKU.SMILING),
	txt("It's been alright?", TAMAKO.NEUTRAL),
	txt("Feels like nothing out of the ordinary has really been happening. By Gensokyo standards, anyway.", TAMAKO.NEUTRAL),
	txt("I'd say it's boring, but... I kind of appreciate just having the time to myself and my friends.", TAMAKO.NEUTRAL),
	txt("Just weird to not have other people's problems to solve for once.", TAMAKO.SMILING),
	txt("... Mhm. I get it.", MYOKU.NEUTRAL),
	txt("Sounds like you've had a good time at least.", MYOKU.SMILING),
	txt("Yeah. What about you, though?", TAMAKO.NEUTRAL),
	txt("Uhm.", MYOKU.NEUTRAL),
	txt("... It's been alright?", MYOKU.NEUTRAL),
	txt("You're not very creative.", TAMAKO.NEUTRAL),
	txt("Uhmmmmm.", MYOKU.NEUTRAL),
	txt("Or subtle.", TAMAKO.AMUSED),
	txt("Sorry. It's... not important. Just felt bored myself recently, despite the new place.", MYOKU.NEUTRAL),
	txt("Okay. But there's more, isn't there?", TAMAKO.NEUTRAL),
	txt("... no?", MYOKU.NEUTRAL),
	txt("The shrine maiden just sighs."),
	txt("Come on, Myoku. I can tell something is bothering you! It's alright if it's too personal, but...", TAMAKO.NEUTRAL),
	txt("I'm always here to help if you need it.", TAMAKO.SMILING),
	txt("... fine.", MYOKU),
	txt("I appreciate it, just feels kind of silly to talk about.", MYOKU),
	txt("It probably isn't as silly as you think it is?", TAMAKO),
	txt("... maybe.", MYOKU),
	txt("Okay, so. My concern right now is that, w-well, I... have a date tonight, and I'm just really anxious about it.", MYOKU),
	txt("Oh?!", TAMAKO),
	txt("It's with that one tanuki you met before, who I've already talked about in the past.", MYOKU),
	txt("I've... never actually been in a relationship with anybody before. I remember a long, long time ago that I wanted to ask her out.", MYOKU),
	txt("But I was too nervous to try, and then we sort of just... fell apart for a good twenty years or so.", MYOKU),
	txt("I don't know what damage might still be there, and I don't know how much of it is my fault.", MYOKU),
	txt("So I want to try and fix everything tonight if I can. It's the matter if I can or not that... still makes me nervous, I guess.", MYOKU),
	txt("... well, it sounds like things are already healing between the two of you, right?", TAMAKO),
	txt("I-I mean, I get it, because I get pretty anxious about stuff like this myself.", TAMAKO),
	txt("But if you're still on good terms with each other, I think it's going to be fine.", TAMAKO),
	txt("Like, it wouldn't just be about having faith in yourself... It would be able having faith in Aisako's ability to trust you.", TAMAKO),
	txt("... yeah. You're right, probably.", MYOKU),
	txt("And you know what? For someone who I have a good few hundred years over, you're pretty wise for your age I think.", MYOKU),
	txt("Huh!?", TAMAKO),
	txt("N-No???", TAMAKO),
	txt("I'm literally just some eighteen year old! I'm stupid!", TAMAKO),
	txt("... nuh uh.", MYOKU),
	txt("F-Fine! Be that way! Throw my own techniques against me!", TAMAKO),
	txt("I only learn what's effective, I'm afraid.", MYOKU),
	txt("But uhm, thank you for helping me here. I'm... admittedly really glad, in hindsight, that you cared.", MYOKU),
	txt("It's no problem, really!", TAMAKO),
	txt("... of course you'd say that.", MYOKU),
	txt("What do you mean by that? I'm being serious!", TAMAKO),
	txt("Blah blah blah, I can't hear you over the sound of you being such a friendly little dork.", MYOKU),
	txt("... Maybe I am one, dork.", TAMAKO),
	txt("Touche.", MYOKU),
	txt("Seriously, though. I really appreciate your advice, Tamako.", MYOKU),
	txt("I'll try my best to be optimistic tonight, and well, hopefully everything will go well from there.", MYOKU),
	txt("That's the spirit! Go and give it your best shot!", TAMAKO),
	txt("I will, don't you worry.", MYOKU),
	txt("... thank you for being my friend, by the way. Sometimes I wonder what things would be like without having you around.", MYOKU),
	txt("At the very least, my life would be a hell of a lot more boring.", MYOKU),
	txt("A-Aw! Thank you.", TAMAKO),
	txt("I'm glad I get to be your friend too.", TAMAKO),
	txt("Mhm.", MYOKU),
	txt("... I should probably be getting ready, actually. I almost lost track of the time.", MYOKU),
	txt("Ah. I'll leave to your own devices then.", TAMAKO),
	txt("Have a great day! Best of luck on your date!", TAMAKO),
	txt("Thanks again for visiting. I hope you have a great day yourself.", MYOKU),
	txt("I'll try!", TAMAKO),
	txt("And with that, the shrine maiden is out the door, and the kitsune is left to her own thoughts... and hopes."),
	txt("Time to make the best of them."),
	/// mountain
	txt("The hour passes, and the kitsune finds themself a cliffface ever familiar to her."),
	txt("For a long, long time, it was the closest thing she had to a home. The closest thing she had to a sanctuary."),
	txt("To her... it was a little slice of her own heaven."),
	txt("Maybe that's why it was still so nostalgic to her."),
	txt("She's pried out of her own thoughts and muses, though, as she sees where her tanuki friend is sitting."),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	txt(""),
	
	];
	
	endevent = c_null;
}